sudo: required
services:
  - docker
before_install:
  - docker build -t annestani/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true annestani/react-test npm test
  
after_success: 
  - docker build -t annestani/multi-client ./client
  - docker build -t annestani/multi-nginx ./nginx
  - docker build -t annestani/multi-server ./server
  - docker build -t annestani/multi-worker ./worker

  # login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # takes the images and push to the docker hub
  - docker push annestani/multi-client
  - docker push annestani/multi-nginx
  - docker push annestani/multi-server
  - docker push annestani/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-374915934591'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  